"""Role Uuser

Revision ID: 799afee9388f
Revises: 
Create Date: 2024-09-02 21:11:49.210476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799afee9388f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    with op.batch_alter_table('rieltors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rieltors', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
