"""added new attr client_id client_id on table messages

Revision ID: a6ad7ba40dd6
Revises: 
Create Date: 2024-08-30 19:50:24.237004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ad7ba40dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rieltor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'rieltors', ['rieltor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rieltor_id')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
